apiVersion: v1
kind: Secret
metadata:
  name: db-secret
type: Opaque
data:
  DB_USERNAME: dXNlcm5hbWU= # Base64-encoded value
  DB_PASSWORD: cGFzc3dvcmQ= # Base64-encoded value

#A Secret is used to store sensitive data, such as passwords or API keys. 
#It can be consumed by containers as environment variables or mounted as files.