version: '3.8'

services:
  app:
    build: ./app/
    ports: 
      - '5000:5000'
  nginx:
    image: nginx:latest
    ports:
      - '80:80'
    volumes:
      - ./app/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app